# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_search/proto/distillation_spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_search/proto/distillation_spec.proto',
  package='learning.adanets.phoenix.meta.proto.distillation_spec',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*model_search/proto/distillation_spec.proto\x12\x35learning.adanets.phoenix.meta.proto.distillation_spec\"n\n\x1d\x41\x64\x61ptivelyBalancingLossesSpec\x12\x17\n\x0fnum_ramp_trials\x18\x01 \x01(\x05\x12\x19\n\x0eminimum_lambda\x18\x02 \x01(\x02:\x01\x31\x12\x19\n\x0emaximum_lambda\x18\x03 \x01(\x02:\x01\x31\"\xb9\x03\n\x10\x44istillationSpec\x12s\n\x11\x64istillation_type\x18\x01 \x01(\x0e\x32X.learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.DistillationType\x12q\n\x13\x62\x61lance_losses_spec\x18\x05 \x01(\x0b\x32T.learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec\x12\x1e\n\x11minimal_pool_size\x18\x02 \x01(\x05:\x03\x31\x30\x30\x12\x16\n\x0btemperature\x18\x03 \x01(\x02:\x01\x31\"\x84\x01\n\x10\x44istillationType\x12\x1d\n\x19UNKNOWN_DISTILLATION_TYPE\x10\x00\x12\x0e\n\nMSE_LOGITS\x10\x01\x12\x0f\n\x0bMSE_SOFTMAX\x10\x02\x12\x11\n\rCROSS_ENTROPY\x10\x03\x12\x1d\n\x19\x41\x44\x41PTIVELY_BALANCE_LOSSES\x10\x05'
)



_DISTILLATIONSPEC_DISTILLATIONTYPE = _descriptor.EnumDescriptor(
  name='DistillationType',
  full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.DistillationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_DISTILLATION_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSE_LOGITS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSE_SOFTMAX', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CROSS_ENTROPY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVELY_BALANCE_LOSSES', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=523,
  serialized_end=655,
)
_sym_db.RegisterEnumDescriptor(_DISTILLATIONSPEC_DISTILLATIONTYPE)


_ADAPTIVELYBALANCINGLOSSESSPEC = _descriptor.Descriptor(
  name='AdaptivelyBalancingLossesSpec',
  full_name='learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_ramp_trials', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec.num_ramp_trials', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minimum_lambda', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec.minimum_lambda', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maximum_lambda', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec.maximum_lambda', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=211,
)


_DISTILLATIONSPEC = _descriptor.Descriptor(
  name='DistillationSpec',
  full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='distillation_type', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.distillation_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance_losses_spec', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.balance_losses_spec', index=1,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minimal_pool_size', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.minimal_pool_size', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec.temperature', index=3,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DISTILLATIONSPEC_DISTILLATIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=655,
)

_DISTILLATIONSPEC.fields_by_name['distillation_type'].enum_type = _DISTILLATIONSPEC_DISTILLATIONTYPE
_DISTILLATIONSPEC.fields_by_name['balance_losses_spec'].message_type = _ADAPTIVELYBALANCINGLOSSESSPEC
_DISTILLATIONSPEC_DISTILLATIONTYPE.containing_type = _DISTILLATIONSPEC
DESCRIPTOR.message_types_by_name['AdaptivelyBalancingLossesSpec'] = _ADAPTIVELYBALANCINGLOSSESSPEC
DESCRIPTOR.message_types_by_name['DistillationSpec'] = _DISTILLATIONSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdaptivelyBalancingLossesSpec = _reflection.GeneratedProtocolMessageType('AdaptivelyBalancingLossesSpec', (_message.Message,), {
  'DESCRIPTOR' : _ADAPTIVELYBALANCINGLOSSESSPEC,
  '__module__' : 'model_search.proto.distillation_spec_pb2'
  # @@protoc_insertion_point(class_scope:learning.adanets.phoenix.meta.proto.distillation_spec.AdaptivelyBalancingLossesSpec)
  })
_sym_db.RegisterMessage(AdaptivelyBalancingLossesSpec)

DistillationSpec = _reflection.GeneratedProtocolMessageType('DistillationSpec', (_message.Message,), {
  'DESCRIPTOR' : _DISTILLATIONSPEC,
  '__module__' : 'model_search.proto.distillation_spec_pb2'
  # @@protoc_insertion_point(class_scope:learning.adanets.phoenix.meta.proto.distillation_spec.DistillationSpec)
  })
_sym_db.RegisterMessage(DistillationSpec)


# @@protoc_insertion_point(module_scope)
