# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_search/proto/transfer_learning_spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_search/proto/transfer_learning_spec.proto',
  package='learning.adanets.phoenix.meta.proto.transfer_learning_spec',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/model_search/proto/transfer_learning_spec.proto\x12:learning.adanets.phoenix.meta.proto.transfer_learning_spec\"\xbc\x03\n\x14TransferLearningSpec\x12\x85\x01\n\x16transfer_learning_type\x18\x01 \x01(\x0e\x32\x65.learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec.TransferLearningType\x12*\n\x1fprevious_trials_discount_factor\x18\x02 \x01(\x02:\x01\x31\x12%\n\x14max_completed_trials\x18\x03 \x01(\x05:\x07\x31\x30\x30\x30\x30\x30\x30\"\xc8\x01\n\x14TransferLearningType\x12\"\n\x1eUNKNOWN_TRANSFER_LEARNING_TYPE\x10\x00\x12\x18\n\x14NO_TRANSFER_LEARNING\x10\x01\x12%\n!UNIFORM_AVERAGE_TRANSFER_LEARNING\x10\x02\x12\x1e\n\x1aSNAPSHOT_TRANSFER_LEARNING\x10\x03\x12+\n\'LOSS_WEIGHTED_AVERAGE_TRANSFER_LEARNING\x10\x04'
)



_TRANSFERLEARNINGSPEC_TRANSFERLEARNINGTYPE = _descriptor.EnumDescriptor(
  name='TransferLearningType',
  full_name='learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec.TransferLearningType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TRANSFER_LEARNING_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_TRANSFER_LEARNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNIFORM_AVERAGE_TRANSFER_LEARNING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SNAPSHOT_TRANSFER_LEARNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOSS_WEIGHTED_AVERAGE_TRANSFER_LEARNING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=356,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERLEARNINGSPEC_TRANSFERLEARNINGTYPE)


_TRANSFERLEARNINGSPEC = _descriptor.Descriptor(
  name='TransferLearningSpec',
  full_name='learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfer_learning_type', full_name='learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec.transfer_learning_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_trials_discount_factor', full_name='learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec.previous_trials_discount_factor', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_completed_trials', full_name='learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec.max_completed_trials', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSFERLEARNINGSPEC_TRANSFERLEARNINGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=556,
)

_TRANSFERLEARNINGSPEC.fields_by_name['transfer_learning_type'].enum_type = _TRANSFERLEARNINGSPEC_TRANSFERLEARNINGTYPE
_TRANSFERLEARNINGSPEC_TRANSFERLEARNINGTYPE.containing_type = _TRANSFERLEARNINGSPEC
DESCRIPTOR.message_types_by_name['TransferLearningSpec'] = _TRANSFERLEARNINGSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransferLearningSpec = _reflection.GeneratedProtocolMessageType('TransferLearningSpec', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERLEARNINGSPEC,
  '__module__' : 'model_search.proto.transfer_learning_spec_pb2'
  # @@protoc_insertion_point(class_scope:learning.adanets.phoenix.meta.proto.transfer_learning_spec.TransferLearningSpec)
  })
_sym_db.RegisterMessage(TransferLearningSpec)


# @@protoc_insertion_point(module_scope)
